/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A;
import AP3.AP3;
import FW.FW;
import WO.WO;
import com.google.common.base.Stopwatch;
import java.awt.Cursor;
import java.beans.PropertyVetoException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.jar.Attributes;
import java.util.jar.JarFile;
import java.util.jar.Manifest;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.WebDriverWait;

/**
 * @author Oleg.Spozito
 */
public class A extends javax.swing.JFrame {
    /**
     * Creates new form A
     */
    public A() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_AP3 = new javax.swing.JMenu();
        jMenu_FW = new javax.swing.JMenu();
        WO = new javax.swing.JMenu();
        ORDERS = new javax.swing.JMenu();
        Reports = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTT");
        setMinimumSize(new java.awt.Dimension(912, 648));
        setSize(new java.awt.Dimension(912, 648));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);
        jDesktopPane1.setName(""); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );

        jMenu_AP3.setBorder(null);
        jMenu_AP3.setText("AP3");
        jMenu_AP3.setName("AP3"); // NOI18N
        jMenu_AP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_AP3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_AP3);

        jMenu_FW.setText("FW");
        jMenu_FW.setName("FW"); // NOI18N
        jMenu_FW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_FWMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_FW);

        WO.setText("WebOrdering");
        WO.setName("FW"); // NOI18N
        WO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WOMouseClicked(evt);
            }
        });
        jMenuBar1.add(WO);

        ORDERS.setText("Orders");
        ORDERS.setContentAreaFilled(false);
        ORDERS.setName("FW"); // NOI18N
        ORDERS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ORDERSMouseClicked(evt);
            }
        });
        jMenuBar1.add(ORDERS);

        Reports.setText("Reports");
        Reports.setContentAreaFilled(false);
        Reports.setName("FW"); // NOI18N
        Reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportsMouseClicked(evt);
            }
        });
        jMenuBar1.add(Reports);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_AP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_AP3MouseClicked
        Open_AP3();
    }//GEN-LAST:event_jMenu_AP3MouseClicked
    private void Open_AP3(){
        setCursor(Cursor.getPredefinedCursor (Cursor.WAIT_CURSOR));
        AP3 ap3 = new AP3();
        ap3.hide();

        this.jDesktopPane1.add(ap3);
        //Thread.sleep(500);
        int Y;
        int X;
        if(F_COUNT > 4) {
            Y = F_COUNT;
            X = F_COUNT - 5;
        }else{
            Y = X = F_COUNT;
        }
        ap3.setLocation(X*20, Y*20);
        try {
            ap3.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(A.class.getName()).log(Level.SEVERE, null, ex);
        } 
        ap3.show();
        ap3.setEnabled(true);
        F_COUNT++; 
        setCursor(Cursor.getPredefinedCursor (Cursor.DEFAULT_CURSOR));        
    }
    private void jMenu_FWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_FWMouseClicked
        setCursor(Cursor.getPredefinedCursor (Cursor.WAIT_CURSOR));
        FW fw = new FW();
        fw.hide();
//        try {
//            ap3.setSelected(true);
//        } catch (PropertyVetoException ex) {
//            Logger.getLogger(A.class.getName()).log(Level.SEVERE, null, ex);
//        }
        this.jDesktopPane1.add(fw);
        //Thread.sleep(500);
        int Y = 0;
        int X = 0;
        if(F_COUNT > 4) {
            Y = F_COUNT;
            X = F_COUNT - 5;
        }else{
            Y = X = F_COUNT;
        }
        fw.setLocation(X*20, Y*20);
        try {
            fw.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(A.class.getName()).log(Level.SEVERE, null, ex);
        }
        fw.show();      
        F_COUNT++; 
        setCursor(Cursor.getPredefinedCursor (Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMenu_FWMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Get_Version();
        Get_User();
        if(!ConnectDB()){
            jMenuBar1.setVisible(false);
            this.setTitle("JTT - no connection to QA DB");
        }else{
            this.setTitle("JTT v1.0.1" + " - " + "User: " + UserID + ", Machine: " + WsID + ", OS: " + WsOS);
        }
        Open_AP3();
    }//GEN-LAST:event_formWindowOpened

    private void ORDERSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ORDERSMouseClicked
        //
    }//GEN-LAST:event_ORDERSMouseClicked

    private void WOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WOMouseClicked
        setCursor(Cursor.getPredefinedCursor (Cursor.WAIT_CURSOR));
        WO wo = new WO();
        wo.hide();
//        try {
//            ap3.setSelected(true);
//        } catch (PropertyVetoException ex) {
//            Logger.getLogger(A.class.getName()).log(Level.SEVERE, null, ex);
//        }
        this.jDesktopPane1.add(wo);
        //Thread.sleep(500);
        int Y = 0;
        int X = 0;
        if(F_COUNT > 4) {
            Y = F_COUNT;
            X = F_COUNT - 5;
        }else{
            Y = X = F_COUNT;
        }
        wo.setLocation(X*20, Y*20);
        try {
            wo.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(A.class.getName()).log(Level.SEVERE, null, ex);
        }
        wo.show();      
        F_COUNT++; 
        setCursor(Cursor.getPredefinedCursor (Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_WOMouseClicked

    private void ReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportsMouseClicked
    private void Get_Version() {
        setCursor(Cursor.getPredefinedCursor (Cursor.WAIT_CURSOR));
        Version =  "?"; 
        try {
            String s = "A.A";
            Version = s.getClass().getPackage().getImplementationVersion(); 
            String path = getClass().getResource("").getPath();
            Manifest m = new JarFile(path).getManifest();
            s = "1";

            Attributes attributes = m.getMainAttributes();
            if (attributes!=null){
                java.util.Iterator it = attributes.keySet().iterator();
                while (it.hasNext()){
                    java.util.jar.Attributes.Name key = (java.util.jar.Attributes.Name) it.next();
                    String keyword = key.toString();
                    if (keyword.equals("Implementation-Version") || keyword.equals("Bundle-Version")){
                        Version = (String) attributes.get(key);
                        break;
                    }
                }
            }
        } catch(Exception ex){
            Version =  ex.getMessage(); 
        }
        setCursor(Cursor.getPredefinedCursor (Cursor.DEFAULT_CURSOR));
    } 
    private void Get_User() {
        setCursor(Cursor.getPredefinedCursor (Cursor.WAIT_CURSOR));
        UserID = System.getProperty("user.name");
        //UserID = "theleepan.sivabalasi";
        WsOS = System.getProperty("os.name");
        try {
            InetAddress addr;
            addr = InetAddress.getLocalHost();
            WsID = addr.getHostName();
        } catch (UnknownHostException ex) { 
            WsID = "Unknown - " + ex.getMessage();
        }
        setCursor(Cursor.getPredefinedCursor (Cursor.DEFAULT_CURSOR));
    } 
    private  boolean ConnectDB() {
        setCursor(Cursor.getPredefinedCursor (Cursor.WAIT_CURSOR));
        boolean OK = false;
        sw1.start();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://dev-digitalhospitality-sql.database.windows.net:1433;database=cdlqadb;user=xttadmin;password=Sp515s10#a;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"); 
            OK = true;
        } catch (SQLException ex) {
            //txtLOG.append("\r\n- SQLException" + ex.getMessage());     
        } catch (ClassNotFoundException ex) {
            //txtLOG.append("\r\n- NotFoundException: " + ex.getMessage());
        }
        //txtLOG.append("\r\n== " + String.format("%.2f", (double)(sw1.elapsed(TimeUnit.MILLISECONDS)) / (long)(1000)) + " sec ==");
        sw1.reset();
        setCursor(Cursor.getPredefinedCursor (Cursor.DEFAULT_CURSOR)); 
        return OK;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); // ==========  Fix to show Windows like c#
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            final A F = new A();
            F.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    try {
                        if(conn != null && !conn.isClosed()){ conn.close(); }
                    }
                    catch (SQLException ex) {
                        Logger.getLogger(AP3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            F.setLocationRelativeTo(null);
            F.setVisible(true);
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Public & Private Variables">
    public static int F_COUNT;
    public static String API_Response_Body = "";
    public static int T_Index;
    public static WebDriver d1;
    public static WebDriver d2;
    public static WebElement e;
    public static WebElement e1;
    public static WebElement e2;
    public static FluentWait wait;
    public static WebDriverWait wait_msg;
    public static WebDriverWait timeout;
    public static List<WebElement> L0 = null;
    public static List<WebElement> L1 = null;
    public static List<WebElement> L2 = null;
    public static List<WebElement> L3 = null;
    public static List<WebElement> Opens = null;
    public static List<WebElement> Closes = null;
    
    public static double sleep = 0.5;
    public static double Timeout = 15;
    public static double Wait = 3;
    public static DateTimeFormatter Time_12_formatter = DateTimeFormatter.ofPattern("hh:mm:ss a"); 
    
    public static String t;
    public static String err;
    public static String F; 
    public static String EX; 
    
    public static String ADMIN_ID;
    public static String ADMIN_PW;
    public static String SM_ID; 
    public static String SM_PW;
    public static String IM_ID; 
    public static String IM_PW;
    
    public static int _t = 0; // Total
    public static int _p = 0; // Passed
    public static int _f = 0; // Failed
    public static int _w = 0; // Warn
    public static boolean FAIL = false;
    public static boolean ALL_DATA = false;
    public static boolean NO_DATA = false;
    
    public static Stopwatch sw1 = Stopwatch.createUnstarted();;
    public static String r_time = "";

    public static String Ver = "";
    public static String url = "";
    public static String appId = "";
    public static String New_ID = "";
    public static String Toast_Msg = "";        
    public static String env = "";
    public static String SITE = "";
    public static String GROUP = "";
    public static String BRAND = "";
    public static String CAN = "CAN";
    public static String GL_MENU = "TIM HORTONS";
    public static String app = "";
    public static String platform = "CDL";
    public static String BrandID = "";
    public static String SiteID = "";
    public static String BaseAPI;
    public static String TZone;
    
    public static String Tab_Name;
    public static String Day;
    public static String Open;
    public static String Close;
    public static String New_From;
    public static String New_To;
    public static String _24;
    public static String Summary;
    public static String r_type;  
    
    public static String P2_TKN = "";
    public static String S_OAuth_TKN = "";
    public static String S_Client_ID = "";
    public static String S_Client_Secret  = "";
    public static String S_Signing_Secret = "";
    public static String S_Hook = "";

    public static Connection conn = null;

    public static final DateTimeFormatter Time_24_formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
    public static final DateTimeFormatter Date_formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
    public static final DateTimeFormatter File_Date_formatter = DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
    
    public static String Version = "";
    public static String UserID = "";
    public static String WsID = "";    
    public static String WsOS = "";  

    public static String SQL = "";   
    public static int t_calls = 0;
    public static double t_min = 0;
    public static double t_max = 0;
    public static double t_avg = 0;
    public static double p_50 = 0;
    public static double p_90 = 0;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ORDERS;
    private javax.swing.JMenu Reports;
    private javax.swing.JMenu WO;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_AP3;
    private javax.swing.JMenu jMenu_FW;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>   
}
