package API;

import static A.A.FAIL;
import static A.A._f;
import static A.A.err;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.joda.time.DateTime;

class promo extends API_GUI {

    protected promo(API_GUI a) {
        app = a.app;
        env = a.env;
        AppID = a.AppID;
        BaseAPI = a.BaseAPI;
        AP3_TKN = a.AP3_TKN;
        CompanyID = a.CompanyID;
        SiteID = a.SiteID;
        BrandID = a.BrandID;
        ParentTest = a.ParentTest;
        ITEMS_IDS = a.ITEMS_IDS;

    }
    private Date release_date = new DateTime(new Date()).plusDays(1).toDate();
    private String RELEASE_DATE_SECONDS = new SimpleDateFormat(111 + "SSS" + 12).format(release_date);
    private String PROMO_START_DAY = new SimpleDateFormat("d").format(release_date);
    private String PROMO_START_MONTH = new SimpleDateFormat("M").format(release_date);
    private String PROMO_START_YEAR = new SimpleDateFormat("yyyy").format(release_date);
    private String PROMO_START_DATE = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").format(release_date);
    private String Promo_Voucher_Id = "";
    private String Promo_Voucher_Code = "";
    private List<String> PROMOTION_IDS = new ArrayList<>();
    private List<String> PROMO_VOUCHER_IDS = new ArrayList<>();
    private List<String> PROMO_VOUCHER_IDS1 = new ArrayList<>();

    protected void run() {
        Auth = "Bearer " + AP3_TKN;  // ===============  AP3 promo ==============================
        JOB_Api_Call("Promo > /promo/company/'CompanyID'/location/group/'SiteID'", "GET",
                BaseAPI + "/promo/company/" + CompanyID + "/location/group/" + SiteID, Auth, "", 200, ParentTest, "no_jira");
        promoVoucherAPIs();
        promoAPIs();
    }

    protected void promoVoucherAPIs() {
        //<editor-fold defaultstate="collapsed" desc="POST promo voucher">
        // Test Scenario 1: Positive flow to POST promo voucher with AMOUNT type
        BODY = "{"
                + "\"code\":\"LOCATION-" + RELEASE_DATE_SECONDS + "\","
                + "\"discount\":{"
                + "\"type\":\"AMOUNT\","
                + "\"amount_off\":1"
                + "},"
                + "\"metadata\":{"
                + "\"name\":\"This is API test promo voucher\","
                + "\"location_id\":\"" + SiteID + "\","
                + "\"is_mealplan_promo\":false"
                + "},"
                + "\"active\":false,"
                + "\"app\":\"" + app + "\""
                + "}";
        JOB_Api_Call("Promotion Voucher - POST add new promo voucher with AMOUNT type", "POST", BaseAPI + "/promo/voucher", Auth, BODY, 200, ParentTest, "no_jira");
        if (json != null) {
            try {
                // Promo_Voucher_Id = json.getString("id");
                Promo_Voucher_Code = json.getString("code");
                PROMO_VOUCHER_IDS.add(json.getString("id"));
            } catch (Exception ex) {
            }
        }

        // Test Scenario 2: Positive flow to POST promo voucher with PERCENTAGE type
        BODY = "{"
                + "\"code\":\"LOCATION-12" + RELEASE_DATE_SECONDS + "\","
                + "\"discount\":{"
                + "\"type\":\"PERCENT\","
                + "\"percent_off\":\"1\""
                + "},"
                + "\"metadata\":{"
                + "\"name\":\"This is API test promo voucher\","
                + "\"location_id\":\"" + SiteID + "\","
                + "\"is_mealplan_promo\":false"
                + "},"
                + "\"active\":false,"
                + "\"app\":\"" + app + "\""
                + "}";
        JOB_Api_Call("Promotion Voucher - POST add new promo voucher  with PERCENTAGE type", "POST", BaseAPI + "/promo/voucher", Auth, BODY, 200, ParentTest, "no_jira");
        if (json != null) {
            try {

                PROMO_VOUCHER_IDS.add(json.getString("id"));
            } catch (Exception ex) {
            }
        }
        // Test Scenario 3: Negative flow to POST promo voucher without code
        BODY = "{"
                + "\"code\":\"\","
                + "\"discount\":{"
                + "\"type\":\"AMOUNT\","
                + "\"amount_off\":1"
                + "},"
                + "\"metadata\":{"
                + "\"name\":\"This is API test promo voucher\","
                + "\"location_id\":\"" + SiteID + "\","
                + "\"is_mealplan_promo\":false"
                + "},"
                + "\"active\":false,"
                + "\"app\":\"" + app + "\""
                + "}";
        JOB_Api_Call("Promotion Voucher - POST Negative flow to add promo voucher without code", "POST", BaseAPI + "/promo/voucher", Auth, BODY, 400, ParentTest, "no_jira");

        // Test Scenario 4: Negative flow to POST promo voucher without promo type
        BODY = "{"
                + "\"code\":\"LOCATION- 12" + RELEASE_DATE_SECONDS + "\","
                + "\"discount\":{"
                + "\"type\":\"\","
                + "\"amount_off\":1"
                + "},"
                + "\"metadata\":{"
                + "\"name\":\"This is API test promo voucher\","
                + "\"location_id\":\"" + SiteID + "\","
                + "\"is_mealplan_promo\":false"
                + "},"
                + "\"active\":false,"
                + "\"app\":\"" + app + "\""
                + "}";
        JOB_Api_Call("Promotion Voucher - POST Negative flow to add promo voucher without valid type", "POST", BaseAPI + "/promo/voucher", Auth, BODY, 400, ParentTest, "no_jira");
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="PUT promo voucher">
        // Test Scenario 1: Positive flow to update newly created promo voucher
        BODY = "{"
                + "\"code\":\"" + Promo_Voucher_Code + "\","
                + "\"discount\":{"
                + "\"type\":\"AMOUNT\","
                + "\"amount_off\":1"
                + "},"
                + "\"metadata\":{"
                + "\"name\":\"This is API test for update promo voucher\","
                + "\"location_id\":\"" + SiteID + "\","
                + "\"is_mealplan_promo\":true"
                + "},"
                + "\"active\":true,"
                + "\"app\":\"" + app + "\""
                + "}";
        JOB_Api_Call("Promotion Voucher - PUT/Update nelwly added promo voucher", "PUT", BaseAPI + "/promo/voucher/" + PROMO_VOUCHER_IDS.get(0), Auth, BODY, 200, ParentTest, "no_jira");

        // Test Scenario 2: Negative flow to update newly created promo voucher without valid code
        BODY = "{"
                + "\"code\":\"\","
                + "\"discount\":{"
                + "\"type\":\"AMOUNT\","
                + "\"amount_off\":1"
                + "},"
                + "\"metadata\":{"
                + "\"name\":\"This is API test for update promo voucher\","
                + "\"location_id\":\"" + SiteID + "\","
                + "\"is_mealplan_promo\":true"
                + "},"
                + "\"active\":true,"
                + "\"app\":\"" + app + "\""
                + "}";
        JOB_Api_Call("Promotion Voucher - PUT/Update nelwly added promo voucher without code", "PUT", BaseAPI + "/promo/voucher/" + PROMO_VOUCHER_IDS.get(0), Auth, BODY, 400, ParentTest, "no_jira");

        // Test Scenario 3: Negative flow to update newly created promo voucher without valid type
        BODY = "{"
                + "\"code\":\"" + Promo_Voucher_Code + "\","
                + "\"discount\":{"
                + "\"type\":\"\","
                + "\"amount_off\":1"
                + "},"
                + "\"metadata\":{"
                + "\"name\":\"This is API test for update promo voucher\","
                + "\"location_id\":\"" + SiteID + "\","
                + "\"is_mealplan_promo\":true"
                + "},"
                + "\"active\":true,"
                + "\"app\":\"" + app + "\""
                + "}";
        JOB_Api_Call("Promotion Voucher - PUT/Update nelwly added promo voucher without type", "PUT", BaseAPI + "/promo/voucher" + PROMO_VOUCHER_IDS.get(0), Auth, BODY, 400, ParentTest, "no_jira");
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="DELETE promo voucher">
        // Test Scenario 1: Positive flow to DELETE newly created promo voucher
        if (PROMO_VOUCHER_IDS != null) {
            for (int i = 0; i < PROMO_VOUCHER_IDS.size(); i++) {
                JOB_Api_Call("Promotion Voucher - DELETE newly added promo voucher : " + PROMO_VOUCHER_IDS.get(i) + "", "DELETE", BaseAPI + "/promo/voucher/" + PROMO_VOUCHER_IDS.get(i), Auth, BODY, 200, ParentTest, "no_jira");
            }
        }
        //</editor-fold>
    }

    protected void promoAPIs() {
        //<editor-fold defaultstate="collapsed" desc="POST promotions">

        if (ITEMS_IDS != null) {
            // Test Scenario 1: Positive flow to POST/ADD new promotion - Limited Time Offer (amount_off)
            BODY = "{"
                    + "\"label\":{"
                    + "\"en\":\"This is API Test for promotion - Limited Time Offer (amount_off)\""
                    + "},"
                    + "\"description\":{"
                    + "\"en\":\"This is test description\""
                    + "},"
                    + "\"multigroup\":\"" + AppID + "\","
                    + "\"company\":\"" + CompanyID + "\","
                    + "\"location_group_ids\":["
                    + "\"" + SiteID + "\""
                    + "],"
                    + "\"type\":\"lto\","
                    + "\"badge\":{"
                    + "\"en\":\"API PROMO\","
                    + "\"fr\":\"API PROMO\""
                    + "},"
                    + "\"status\":\"scheduled\","
                    + "\"items\":{"
                    + "\"main\":["
                    + "{"
                    + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                    + "\"quantity\":1,"
                    + "\"price\":{"
                    + "\"amount\":5"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"French vanilla\""
                    + "},"
                    + "\"discount\":{"
                    + "\"amount_off\":1,"
                    + "\"percent_off\":null"
                    + "}"
                    + "}"
                    + "],"
                    + "\"additional\":["
                    + "]"
                    + "},"
                    + "\"calendar\":{"
                    + "\"events\":["
                    + "{"
                    + "\"data\":{"
                    + "\"calendar\":\"hours\""
                    + "},"
                    + "\"schedule\":{"
                    + "\"start\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":0,"
                    + "\"minute\":0"
                    + "},"
                    + "\"end\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":23,"
                    + "\"minute\":59"
                    + "},"
                    + "\"times\":["
                    + "\"00:00\""
                    + "],"
                    + "\"duration\":720,"
                    + "\"durationUnit\":\"minutes\","
                    + "\"dayOfWeek\":["
                    + "0,"
                    + "1,"
                    + "2,"
                    + "3,"
                    + "4,"
                    + "5,"
                    + "6"
                    + "]"
                    + "}"
                    + "}"
                    + "],"
                    + "\"timezones\":{"
                    + "\"" + SiteID + "\":\"America/Toronto\""
                    + "}"
                    + "}"
                    + "}";
            JOB_Api_Call("Promotion - POST Positive flow to add new promotion - Limited Time Offer (amount_off)", "POST", BaseAPI + "/promo", Auth, BODY, 200, ParentTest, "no_jira");
            if (json != null) {
                try {

                    PROMOTION_IDS.add(json.getString("id"));
                } catch (Exception ex) {
                }
            }

            // Test Scenario 2: Positive flow to POST/ADD new promotion - BOGO
            if (ITEMS_IDS.size() >= 1) {
                BODY = "{"
                        + "\"label\":{"
                        + "\"en\":\"This is API test Positive flow to POST/ADD new promotion - BOGO\""
                        + "},"
                        + "\"description\":{"
                        + "\"en\":\"BOGO promo\""
                        + "},"
                        + "\"multigroup\":\"" + AppID + "\","
                        + "\"company\":\"" + CompanyID + "\","
                        + "\"location_group_ids\":["
                        + "\"" + SiteID + "\""
                        + "],"
                        + "\"type\":\"bogo\","
                        + "\"badge\":{"
                        + "\"en\":\"BOGO promo\","
                        + "\"fr\":\"BOGO promo\""
                        + "},"
                        + "\"status\":\"scheduled\","
                        + "\"items\":{"
                        + "\"main\":["
                        + "{"
                        + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                        + "\"quantity\":1,"
                        + "\"price\":{"
                        + "\"amount\":1"
                        + "},"
                        + "\"label\":{"
                        + "\"en\":\"BOGO promo\""
                        + "},"
                        + "\"discount\":{"
                        + "\"amount_off\":null,"
                        + "\"percent_off\":null"
                        + "}"
                        + "}"
                        + "],"
                        + "\"additional\":["
                        + "{"
                        + "\"id\":\"" + ITEMS_IDS.get(1) + "\","
                        + "\"quantity\":1,"
                        + "\"price\":{"
                        + "\"amount\":5"
                        + "},"
                        + "\"label\":{"
                        + "\"en\":\"French vanilla\""
                        + "},"
                        + "\"discount\":{"
                        + "\"amount_off\":5,"
                        + "\"percent_off\":null"
                        + "}"
                        + "}"
                        + "]"
                        + "},"
                        + "\"calendar\":{"
                        + "\"events\":["
                        + "{"
                        + "\"data\":{"
                        + "\"calendar\":\"hours\""
                        + "},"
                        + "\"schedule\":{"
                        + "\"start\":{"
                        + "\"year\":" + PROMO_START_YEAR + ","
                        + "\"month\":" + PROMO_START_MONTH + ","
                        + "\"day\":" + PROMO_START_DAY + ","
                        + "\"hour\":0,"
                        + "\"minute\":0"
                        + "},"
                        + "\"end\":{"
                        + "\"year\":" + PROMO_START_YEAR + ","
                        + "\"month\":" + PROMO_START_MONTH + ","
                        + "\"day\":" + PROMO_START_DAY + ","
                        + "\"hour\":23,"
                        + "\"minute\":59"
                        + "},"
                        + "\"times\":["
                        + "\"00:00\""
                        + "],"
                        + "\"duration\":0,"
                        + "\"durationUnit\":\"minutes\","
                        + "\"dayOfWeek\":["
                        + "0"
                        + "]"
                        + "}"
                        + "}"
                        + "],"
                        + "\"timezones\":{"
                        + "\"" + SiteID + "\":\"America/Toronto\""
                        + "}"
                        + "}"
                        + "}";
                JOB_Api_Call("Promotion - POST Positive flow to POST/ADD new promotion - BOGO", "POST", BaseAPI + "/promo", Auth, BODY, 200, ParentTest, "no_jira");
                if (json != null) {
                    try {

                        PROMOTION_IDS.add(json.getString("id"));
                    } catch (Exception ex) {
                    }
                }

                // Test Scenario 3: Positive flow to POST/ADD new promotion - Bundle
                BODY = "{"
                        + "\"label\":{"
                        + "\"en\":\"This is API test for BUNDLE\""
                        + "},"
                        + "\"description\":{"
                        + "\"en\":\"Description\""
                        + "},"
                        + "\"multigroup\":\"" + AppID + "\","
                        + "\"company\":\"" + CompanyID + "\","
                        + "\"location_group_ids\":["
                        + "\"" + SiteID + "\""
                        + "],"
                        + "\"type\":\"bundle\","
                        + "\"badge\":{"
                        + "\"en\":\"BUNDEL PROMO\","
                        + "\"fr\":\"BUNDEL PROMO\""
                        + "},"
                        + "\"status\":\"scheduled\","
                        + "\"items\":{"
                        + "\"main\":["
                        + "{"
                        + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                        + "\"quantity\":1,"
                        + "\"price\":{"
                        + "\"amount\":1"
                        + "},"
                        + "\"label\":{"
                        + "\"en\":\"ds test 2\""
                        + "},"
                        + "\"discount\":{"
                        + "\"amount_off\":null,"
                        + "\"percent_off\":null"
                        + "}"
                        + "},"
                        + "{"
                        + "\"id\":\"" + ITEMS_IDS.get(1) + "\","
                        + "\"quantity\":1,"
                        + "\"price\":{"
                        + "\"amount\":5"
                        + "},"
                        + "\"label\":{"
                        + "\"en\":\"French vanilla\""
                        + "},"
                        + "\"discount\":{"
                        + "\"amount_off\":null,"
                        + "\"percent_off\":null"
                        + "}"
                        + "}"
                        + "],"
                        + "\"additional\":["
                        + "]"
                        + "},"
                        + "\"calendar\":{"
                        + "\"events\":["
                        + "{"
                        + "\"data\":{"
                        + "\"calendar\":\"hours\""
                        + "},"
                        + "\"schedule\":{"
                        + "\"start\":{"
                        + "\"year\":" + PROMO_START_YEAR + ","
                        + "\"month\":" + PROMO_START_MONTH + ","
                        + "\"day\":" + PROMO_START_DAY + ","
                        + "\"hour\":0,"
                        + "\"minute\":0"
                        + "},"
                        + "\"end\":{"
                        + "\"year\":" + PROMO_START_YEAR + ","
                        + "\"month\":" + PROMO_START_MONTH + ","
                        + "\"day\":" + PROMO_START_DAY + ","
                        + "\"hour\":23,"
                        + "\"minute\":59"
                        + "},"
                        + "\"times\":["
                        + "\"00:00\""
                        + "],"
                        + "\"duration\":0,"
                        + "\"durationUnit\":\"minutes\","
                        + "\"dayOfWeek\":["
                        + "0,"
                        + "1"
                        + "]"
                        + "}"
                        + "}"
                        + "],"
                        + "\"timezones\":{"
                        + "\"" + SiteID + "\":\"America/Toronto\""
                        + "}"
                        + "}"
                        + "}";
                JOB_Api_Call("Promotion - POST Positive flow to POST/ADD new promotion - Bundle", "POST", BaseAPI + "/promo", Auth, BODY, 200, ParentTest, "no_jira");
                if (json != null) {
                    try {

                        PROMOTION_IDS.add(json.getString("id"));
                    } catch (Exception ex) {
                    }
                }
            } else {
                //Add Fail block & Message
            }
            // Test Scenario 4: Negative flow to POST/ADD new promotion without valid promo label
            BODY = "{"
                    + "\"label\":{"
                    + "\"en\":\"\""
                    + "},"
                    + "\"description\":{"
                    + "\"en\":\"This is test description\""
                    + "},"
                    + "\"multigroup\":\"" + AppID + "\","
                    + "\"company\":\"" + CompanyID + "\","
                    + "\"location_group_ids\":["
                    + "\"" + SiteID + "\""
                    + "],"
                    + "\"type\":\"lto\","
                    + "\"badge\":{"
                    + "\"en\":\"API PROMO\","
                    + "\"fr\":\"API PROMO\""
                    + "},"
                    + "\"status\":\"scheduled\","
                    + "\"items\":{"
                    + "\"main\":["
                    + "{"
                    + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                    + "\"quantity\":1,"
                    + "\"price\":{"
                    + "\"amount\":5"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"French vanilla\""
                    + "},"
                    + "\"discount\":{"
                    + "\"amount_off\":1,"
                    + "\"percent_off\":null"
                    + "}"
                    + "}"
                    + "],"
                    + "\"additional\":["
                    + "]"
                    + "},"
                    + "\"calendar\":{"
                    + "\"events\":["
                    + "{"
                    + "\"data\":{"
                    + "\"calendar\":\"hours\""
                    + "},"
                    + "\"schedule\":{"
                    + "\"start\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":0,"
                    + "\"minute\":0"
                    + "},"
                    + "\"end\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":23,"
                    + "\"minute\":59"
                    + "},"
                    + "\"times\":["
                    + "\"00:00\""
                    + "],"
                    + "\"duration\":720,"
                    + "\"durationUnit\":\"minutes\","
                    + "\"dayOfWeek\":["
                    + "0,"
                    + "1,"
                    + "2,"
                    + "3,"
                    + "4,"
                    + "5,"
                    + "6"
                    + "]"
                    + "}"
                    + "}"
                    + "],"
                    + "\"timezones\":{"
                    + "\"" + SiteID + "\":\"America/Toronto\""
                    + "}"
                    + "}"
                    + "}";
            JOB_Api_Call("Promotion - POST Negative flow to POST/ADD new promotion without valid promo label", "POST", BaseAPI + "/promo", Auth, BODY, 400, ParentTest, "no_jira");

            // Test Scenario 5: Negative flow to POST/ADD new promotion without valid Multipgroup/APP Id
            BODY = "{"
                    + "\"label\":{"
                    + "\"en\":\"This is API test for BUNDLE\""
                    + "},"
                    + "},"
                    + "\"description\":{"
                    + "\"en\":\"This is test description\""
                    + "},"
                    + "\"multigroup\":\"\","
                    + "\"company\":\"" + CompanyID + "\","
                    + "\"location_group_ids\":["
                    + "\"" + SiteID + "\""
                    + "],"
                    + "\"type\":\"lto\","
                    + "\"badge\":{"
                    + "\"en\":\"API PROMO\","
                    + "\"fr\":\"API PROMO\""
                    + "},"
                    + "\"status\":\"scheduled\","
                    + "\"items\":{"
                    + "\"main\":["
                    + "{"
                    + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                    + "\"quantity\":1,"
                    + "\"price\":{"
                    + "\"amount\":5"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"French vanilla\""
                    + "},"
                    + "\"discount\":{"
                    + "\"amount_off\":1,"
                    + "\"percent_off\":null"
                    + "}"
                    + "}"
                    + "],"
                    + "\"additional\":["
                    + "]"
                    + "},"
                    + "\"calendar\":{"
                    + "\"events\":["
                    + "{"
                    + "\"data\":{"
                    + "\"calendar\":\"hours\""
                    + "},"
                    + "\"schedule\":{"
                    + "\"start\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":0,"
                    + "\"minute\":0"
                    + "},"
                    + "\"end\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":23,"
                    + "\"minute\":59"
                    + "},"
                    + "\"times\":["
                    + "\"00:00\""
                    + "],"
                    + "\"duration\":720,"
                    + "\"durationUnit\":\"minutes\","
                    + "\"dayOfWeek\":["
                    + "0,"
                    + "1,"
                    + "2,"
                    + "3,"
                    + "4,"
                    + "5,"
                    + "6"
                    + "]"
                    + "}"
                    + "}"
                    + "],"
                    + "\"timezones\":{"
                    + "\"" + SiteID + "\":\"America/Toronto\""
                    + "}"
                    + "}"
                    + "}";
            JOB_Api_Call("Promotion - POST Negative flow to POST/ADD new promotion without valid Multipgroup/APP Id", "POST", BaseAPI + "/promo", Auth, BODY, 400, ParentTest, "no_jira");

            // Test Scenario 6: Negative flow to POST/ADD new promotion without valid Company/Group Id
            BODY = "{"
                    + "\"label\":{"
                    + "\"en\":\"This is API test for BUNDLE\""
                    + "},"
                    + "},"
                    + "\"description\":{"
                    + "\"en\":\"This is test description\""
                    + "},"
                    + "\"multigroup\":\"" + AppID + "\","
                    + "\"company\":\"\","
                    + "\"location_group_ids\":["
                    + "\"" + SiteID + "\""
                    + "],"
                    + "\"type\":\"lto\","
                    + "\"badge\":{"
                    + "\"en\":\"API PROMO\","
                    + "\"fr\":\"API PROMO\""
                    + "},"
                    + "\"status\":\"scheduled\","
                    + "\"items\":{"
                    + "\"main\":["
                    + "{"
                    + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                    + "\"quantity\":1,"
                    + "\"price\":{"
                    + "\"amount\":5"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"French vanilla\""
                    + "},"
                    + "\"discount\":{"
                    + "\"amount_off\":1,"
                    + "\"percent_off\":null"
                    + "}"
                    + "}"
                    + "],"
                    + "\"additional\":["
                    + "]"
                    + "},"
                    + "\"calendar\":{"
                    + "\"events\":["
                    + "{"
                    + "\"data\":{"
                    + "\"calendar\":\"hours\""
                    + "},"
                    + "\"schedule\":{"
                    + "\"start\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":0,"
                    + "\"minute\":0"
                    + "},"
                    + "\"end\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":23,"
                    + "\"minute\":59"
                    + "},"
                    + "\"times\":["
                    + "\"00:00\""
                    + "],"
                    + "\"duration\":720,"
                    + "\"durationUnit\":\"minutes\","
                    + "\"dayOfWeek\":["
                    + "0,"
                    + "1,"
                    + "2,"
                    + "3,"
                    + "4,"
                    + "5,"
                    + "6"
                    + "]"
                    + "}"
                    + "}"
                    + "],"
                    + "\"timezones\":{"
                    + "\"" + SiteID + "\":\"America/Toronto\""
                    + "}"
                    + "}"
                    + "}";
            JOB_Api_Call("Promotion - POST Negative flow to POST/ADD new promotion without valid Company/Group Id", "POST", BaseAPI + "/promo", Auth, BODY, 400, ParentTest, "no_jira");

            // Test Scenario 7: Negative flow to POST/ADD new promotion without valid Secror/Site Id
            BODY = "{"
                    + "\"label\":{"
                    + "\"en\":\"This is API test for BUNDLE\""
                    + "},"
                    + "},"
                    + "\"description\":{"
                    + "\"en\":\"This is test description\""
                    + "},"
                    + "\"multigroup\":\"" + AppID + "\","
                    + "\"company\":\"" + CompanyID + "\","
                    + "\"location_group_ids\":["
                    + "\"\""
                    + "],"
                    + "\"type\":\"lto\","
                    + "\"badge\":{"
                    + "\"en\":\"API PROMO\","
                    + "\"fr\":\"API PROMO\""
                    + "},"
                    + "\"status\":\"scheduled\","
                    + "\"items\":{"
                    + "\"main\":["
                    + "{"
                    + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                    + "\"quantity\":1,"
                    + "\"price\":{"
                    + "\"amount\":5"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"French vanilla\""
                    + "},"
                    + "\"discount\":{"
                    + "\"amount_off\":1,"
                    + "\"percent_off\":null"
                    + "}"
                    + "}"
                    + "],"
                    + "\"additional\":["
                    + "]"
                    + "},"
                    + "\"calendar\":{"
                    + "\"events\":["
                    + "{"
                    + "\"data\":{"
                    + "\"calendar\":\"hours\""
                    + "},"
                    + "\"schedule\":{"
                    + "\"start\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":0,"
                    + "\"minute\":0"
                    + "},"
                    + "\"end\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":23,"
                    + "\"minute\":59"
                    + "},"
                    + "\"times\":["
                    + "\"00:00\""
                    + "],"
                    + "\"duration\":720,"
                    + "\"durationUnit\":\"minutes\","
                    + "\"dayOfWeek\":["
                    + "0,"
                    + "1,"
                    + "2,"
                    + "3,"
                    + "4,"
                    + "5,"
                    + "6"
                    + "]"
                    + "}"
                    + "}"
                    + "],"
                    + "\"timezones\":{"
                    + "\"" + SiteID + "\":\"America/Toronto\""
                    + "}"
                    + "}"
                    + "}";
            JOB_Api_Call("Promotion - POST Negative flow to POST/ADD new promotion without valid Secror/Site Id", "POST", BaseAPI + "/promo", Auth, BODY, 400, ParentTest, "no_jira");
        } else {
            _f++;
            FAIL = true;
            err = "No Item Id found to add promotions";
        }
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="PUT promotions">
        if (ITEMS_IDS != null) {
            //Test Scenario 1: Positive flow to update & PAUSE newly added promotion 
            BODY = "{"
                    + "\"id\":\"" + PROMOTION_IDS.get(0) + "\","
                    + "\"badge\":{"
                    + "\"en\":\"API PROMO-UPDATE\","
                    + "\"fr\":\"API PROMO-UPDATE\""
                    + "},"
                    + "\"calendar\":{"
                    + "\"events\":["
                    + "{"
                    + "\"data\":{"
                    + "\"calendar\":\"hours\""
                    + "},"
                    + "\"schedule\":{"
                    + "\"start\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":0,"
                    + "\"minute\":0"
                    + "},"
                    + "\"end\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":23,"
                    + "\"minute\":59"
                    + "},"
                    + "\"times\":["
                    + "\"00:00\""
                    + "],"
                    + "\"duration\":720,"
                    + "\"durationUnit\":\"minutes\","
                    + "\"dayOfWeek\":["
                    + "5,"
                    + "6"
                    + "]"
                    + "}"
                    + "}"
                    + "],"
                    + "\"timezones\":{"
                    + "\"" + SiteID + "\":\"America/Toronto\""
                    + "}"
                    + "},"
                    + "\"company\":\"" + CompanyID + "\","
                    + "\"description\":{"
                    + "\"en\":\"This is test update description\""
                    + "},"
                    + "\"items\":{"
                    + "\"main\":["
                    + "{"
                    + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                    + "\"quantity\":1,"
                    + "\"price\":{"
                    + "\"amount\":5"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"French vanilla-Update\""
                    + "},"
                    + "\"discount\":{"
                    + "\"amount_off\":null,"
                    + "\"percent_off\":2"
                    + "}"
                    + "}"
                    + "],"
                    + "\"additional\":["
                    + "]"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"This is API Test for promotion - Limited Time Offer (amount_off)\""
                    + "},"
                    + "\"location_group_ids\":["
                    + "\"" + SiteID + "\""
                    + "],"
                    + "\"multigroup\":\"" + AppID + "\","
                    + "\"status\":\"paused\","
                    + "\"meta\":{"
                    + "\"hours\":["
                    + "{"
                    + "\"start\":\"" + PROMO_START_DATE + "\","
                    + "\"end\":\"" + PROMO_START_DATE + "\""
                    + "}"
                    + "],"
                    + "\"promo_start\":\"" + PROMO_START_DATE + "\","
                    + "\"promo_end\":\"" + PROMO_START_DATE + "\""
                    + "},"
                    + "\"type\":\"lto\""
                    + "}";
            JOB_Api_Call("Promotion - PUT Positive flow to update & PAUSE newly added promotion", "PUT", BaseAPI + "/promo/" + PROMOTION_IDS.get(0), Auth, BODY, 200, ParentTest, "no_jira");

            // Test Scenario 2: Positive flow to update newly added promotion - Limited Time Offer (Percent_off)
            BODY = "{"
                    + "\"id\":\"" + PROMOTION_IDS.get(0) + "\","
                    + "\"badge\":{"
                    + "\"en\":\"API PROMO\","
                    + "\"fr\":\"API PROMO\""
                    + "},"
                    + "\"calendar\":{"
                    + "\"events\":["
                    + "{"
                    + "\"data\":{"
                    + "\"calendar\":\"hours\""
                    + "},"
                    + "\"schedule\":{"
                    + "\"start\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":0,"
                    + "\"minute\":0"
                    + "},"
                    + "\"end\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":23,"
                    + "\"minute\":59"
                    + "},"
                    + "\"times\":["
                    + "\"00:00\""
                    + "],"
                    + "\"duration\":720,"
                    + "\"durationUnit\":\"minutes\","
                    + "\"dayOfWeek\":["
                    + "0,"
                    + "1,"
                    + "2,"
                    + "3,"
                    + "4,"
                    + "5,"
                    + "6"
                    + "]"
                    + "}"
                    + "}"
                    + "],"
                    + "\"timezones\":{"
                    + "\"" + SiteID + "\":\"America/Toronto\""
                    + "}"
                    + "},"
                    + "\"company\":\"" + CompanyID + "\","
                    + "\"description\":{"
                    + "\"en\":\"This is test description\""
                    + "},"
                    + "\"items\":{"
                    + "\"main\":["
                    + "{"
                    + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                    + "\"quantity\":1,"
                    + "\"price\":{"
                    + "\"amount\":5"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"French vanilla\""
                    + "},"
                    + "\"discount\":{"
                    + "\"amount_off\":null,"
                    + "\"percent_off\":1"
                    + "}"
                    + "}"
                    + "],"
                    + "\"additional\":["
                    + "]"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"This is API Test for promotion - Limited Time Offer (amount_off)\""
                    + "},"
                    + "\"location_group_ids\":["
                    + "\"" + SiteID + "\""
                    + "],"
                    + "\"multigroup\":\"" + AppID + "\","
                    + "\"status\":\"active\","
                    + "\"meta\":{"
                    + "\"hours\":["
                    + "{"
                    + "\"start\":\"" + PROMO_START_DATE + "\","
                    + "\"end\":\"" + PROMO_START_DATE + "\""
                    + "}"
                    + "],"
                    + "\"promo_start\":\"" + PROMO_START_DATE + "\","
                    + "\"promo_end\":\"" + PROMO_START_DATE + "\""
                    + "},"
                    + "\"type\":\"lto\""
                    + "}";
            JOB_Api_Call("Promotion - PUT Positive flow to update newly added promotion - Limited Time Offer (Percent_off)", "PUT", BaseAPI + "/promo/" + PROMOTION_IDS.get(0), Auth, BODY, 200, ParentTest, "no_jira");

            // Test Scenario 3: Positive flow to update newly added promotion - BOGO
            if (ITEMS_IDS.size() >= 1) {
                BODY = "{"
                        + "\"id\":\"" + PROMOTION_IDS.get(1) + "\","
                        + "\"badge\":{"
                        + "\"en\":\"Promo -BOGO\","
                        + "\"fr\":\"Promo -BOGO\""
                        + "},"
                        + "\"calendar\":{"
                        + "\"events\":["
                        + "{"
                        + "\"data\":{"
                        + "\"calendar\":\"hours\""
                        + "},"
                        + "\"schedule\":{"
                        + "\"start\":{"
                        + "\"year\":" + PROMO_START_YEAR + ","
                        + "\"month\":" + PROMO_START_MONTH + ","
                        + "\"day\":" + PROMO_START_DAY + ","
                        + "\"hour\":0,"
                        + "\"minute\":0"
                        + "},"
                        + "\"end\":{"
                        + "\"year\":" + PROMO_START_YEAR + ","
                        + "\"month\":" + PROMO_START_MONTH + ","
                        + "\"day\":" + PROMO_START_DAY + ","
                        + "\"hour\":23,"
                        + "\"minute\":59"
                        + "},"
                        + "\"times\":["
                        + "\"14:00\""
                        + "],"
                        + "\"duration\":360,"
                        + "\"durationUnit\":\"minutes\","
                        + "\"dayOfWeek\":["
                        + "5,"
                        + "1,"
                        + "3"
                        + "]"
                        + "}"
                        + "}"
                        + "],"
                        + "\"timezones\":{"
                        + "\"" + SiteID + "\":\"America/Toronto\""
                        + "}"
                        + "},"
                        + "\"company\":\"" + CompanyID + "\","
                        + "\"description\":{"
                        + "\"en\":\"BOGO description\""
                        + "},"
                        + "\"items\":{"
                        + "\"main\":["
                        + "{"
                        + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                        + "\"quantity\":1,"
                        + "\"price\":{"
                        + "\"amount\":5"
                        + "},"
                        + "\"label\":{"
                        + "\"en\":\"French vanilla\""
                        + "},"
                        + "\"discount\":{"
                        + "\"amount_off\":null,"
                        + "\"percent_off\":null"
                        + "}"
                        + "}"
                        + "],"
                        + "\"additional\":["
                        + "{"
                        + "\"id\":\"" + ITEMS_IDS.get(1) + "\","
                        + "\"quantity\":1,"
                        + "\"price\":{"
                        + "\"amount\":7"
                        + "},"
                        + "\"label\":{"
                        + "\"en\":\"Tuna Melt\""
                        + "},"
                        + "\"discount\":{"
                        + "\"amount_off\":1,"
                        + "\"percent_off\":null"
                        + "}"
                        + "},"
                        + "{"
                        + "\"id\":\"" + ITEMS_IDS.get(2) + "\","
                        + "\"quantity\":1,"
                        + "\"price\":{"
                        + "\"amount\":5"
                        + "},"
                        + "\"label\":{"
                        + "\"en\":\"French vanilla\""
                        + "},"
                        + "\"discount\":{"
                        + "\"amount_off\":null,"
                        + "\"percent_off\":1"
                        + "}"
                        + "}"
                        + "]"
                        + "},"
                        + "\"label\":{"
                        + "\"en\":\"This is API test Update\""
                        + "},"
                        + "\"location_group_ids\":["
                        + "\"" + SiteID + "\""
                        + "],"
                        + "\"multigroup\":\"" + AppID + "\","
                        + "\"status\":\"expired\","
                        + "\"meta\":{"
                        + "\"hours\":["
                        + "]"
                        + "},"
                        + "\"type\":\"bogo\""
                        + "}";
                JOB_Api_Call("Promotion - Positive flow to update newly added promotion - BOGO", "PUT", BaseAPI + "/promo/" + PROMOTION_IDS.get(1), Auth, BODY, 200, ParentTest, "no_jira");
                // Test Scenario 4: Positive flow to update newly added - Bundle
                BODY = "{"
                        + "\"id\":\"" + PROMOTION_IDS.get(2) + "\","
                        + "\"badge\":{"
                        + "\"en\":\"BUNDEL PROMO\","
                        + "\"fr\":\"BUNDEL PROMO\""
                        + "},"
                        + "\"calendar\":{"
                        + "\"events\":["
                        + "{"
                        + "\"data\":{"
                        + "\"calendar\":\"hours\""
                        + "},"
                        + "\"schedule\":{"
                        + "\"start\":{"
                        + "\"year\":" + PROMO_START_YEAR + ","
                        + "\"month\":" + PROMO_START_MONTH + ","
                        + "\"day\":" + PROMO_START_DAY + ","
                        + "\"hour\":0,"
                        + "\"minute\":0"
                        + "},"
                        + "\"end\":{"
                        + "\"year\":" + PROMO_START_YEAR + ","
                        + "\"month\":" + PROMO_START_MONTH + ","
                        + "\"day\":" + PROMO_START_DAY + ","
                        + "\"hour\":23,"
                        + "\"minute\":59"
                        + "},"
                        + "\"times\":["
                        + "\"00:00\""
                        + "],"
                        + "\"duration\":0,"
                        + "\"durationUnit\":\"minutes\","
                        + "\"dayOfWeek\":["
                        + "2,"
                        + "3,"
                        + "4,"
                        + "5"
                        + "]"
                        + "}"
                        + "}"
                        + "],"
                        + "\"timezones\":{"
                        + "\"" + SiteID + "\":\"America/Toronto\""
                        + "}"
                        + "},"
                        + "\"company\":\"" + CompanyID + "\","
                        + "\"description\":{"
                        + "\"en\":\"This is description update\""
                        + "},"
                        + "\"items\":{"
                        + "\"main\":["
                        + "{"
                        + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                        + "\"quantity\":1,"
                        + "\"price\":{"
                        + "\"amount\":1"
                        + "},"
                        + "\"label\":{"
                        + "\"en\":\"ds test 2\""
                        + "},"
                        + "\"discount\":{"
                        + "\"percent_off\":1"
                        + "}"
                        + "},"
                        + "{"
                        + "\"id\":\"" + ITEMS_IDS.get(1) + "\","
                        + "\"quantity\":1,"
                        + "\"price\":{"
                        + "\"amount\":5"
                        + "},"
                        + "\"label\":{"
                        + "\"en\":\"French vanilla\""
                        + "},"
                        + "\"discount\":{"
                        + "\"amount_off\":2"
                        + "}"
                        + "}"
                        + "],"
                        + "\"additional\":["
                        + "]"
                        + "},"
                        + "\"label\":{"
                        + "\"en\":\"This is API test for Update BUNDLE\""
                        + "},"
                        + "\"location_group_ids\":["
                        + "\"" + SiteID + "\""
                        + "],"
                        + "\"multigroup\":\"" + AppID + "\","
                        + "\"status\":\"active\","
                        + "\"meta\":{"
                        + "\"hours\":["
                        + "],"
                        + "\"start\":\"" + PROMO_START_DATE + "\","
                        + "\"end\":\"" + PROMO_START_DATE + "\""
                        + "},"
                        + "\"type\":\"bundle\""
                        + "}";
                JOB_Api_Call("Promotion - PUT Positive flow to update newly added - Bundle", "PUT", BaseAPI + "/promo/" + PROMOTION_IDS.get(2), Auth, BODY, 200, ParentTest, "no_jira");
            } else {
                //Add fail bllock, when Item ID is null
            }
            // Test Scenario 5: Negative flow to update newly added promotion without valid promo label
            BODY = "{"
                    + "\"id\":\"" + PROMOTION_IDS.get(0) + "\","
                    + "\"badge\":{"
                    + "\"en\":\"API PROMO-UPDATE\","
                    + "\"fr\":\"API PROMO-UPDATE\""
                    + "},"
                    + "\"calendar\":{"
                    + "\"events\":["
                    + "{"
                    + "\"data\":{"
                    + "\"calendar\":\"hours\""
                    + "},"
                    + "\"schedule\":{"
                    + "\"start\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":0,"
                    + "\"minute\":0"
                    + "},"
                    + "\"end\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":23,"
                    + "\"minute\":59"
                    + "},"
                    + "\"times\":["
                    + "\"00:00\""
                    + "],"
                    + "\"duration\":720,"
                    + "\"durationUnit\":\"minutes\","
                    + "\"dayOfWeek\":["
                    + "5,"
                    + "6"
                    + "]"
                    + "}"
                    + "}"
                    + "],"
                    + "\"timezones\":{"
                    + "\"" + SiteID + "\":\"America/Toronto\""
                    + "}"
                    + "},"
                    + "\"company\":\"" + CompanyID + "\","
                    + "\"description\":{"
                    + "\"en\":\"This is test update description\""
                    + "},"
                    + "\"items\":{"
                    + "\"main\":["
                    + "{"
                    + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                    + "\"quantity\":1,"
                    + "\"price\":{"
                    + "\"amount\":5"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"French vanilla-Update\""
                    + "},"
                    + "\"discount\":{"
                    + "\"amount_off\":null,"
                    + "\"percent_off\":2"
                    + "}"
                    + "}"
                    + "],"
                    + "\"additional\":["
                    + "]"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"\""
                    + "},"
                    + "\"location_group_ids\":["
                    + "\"" + SiteID + "\""
                    + "],"
                    + "\"multigroup\":\"" + AppID + "\","
                    + "\"status\":\"paused\","
                    + "\"meta\":{"
                    + "\"hours\":["
                    + "{"
                    + "\"start\":\"" + PROMO_START_DATE + "\","
                    + "\"end\":\"" + PROMO_START_DATE + "\""
                    + "}"
                    + "],"
                    + "\"promo_start\":\"" + PROMO_START_DATE + "\","
                    + "\"promo_end\":\"" + PROMO_START_DATE + "\""
                    + "},"
                    + "\"type\":\"lto\""
                    + "}";
            JOB_Api_Call("Promotion - PUT Negative flow to update newly added promotion without valid promo label", "PUT", BaseAPI + "/promo/" + PROMOTION_IDS.get(0), Auth, BODY, 400, ParentTest, "no_jira");

            // Test Scenario 6: Negative flow to update newly added promotion without valid Multipgroup/APP Id
            BODY = "{"
                    + "\"id\":\"" + PROMOTION_IDS.get(0) + "\","
                    + "\"badge\":{"
                    + "\"en\":\"API PROMO-UPDATE\","
                    + "\"fr\":\"API PROMO-UPDATE\""
                    + "},"
                    + "\"calendar\":{"
                    + "\"events\":["
                    + "{"
                    + "\"data\":{"
                    + "\"calendar\":\"hours\""
                    + "},"
                    + "\"schedule\":{"
                    + "\"start\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":0,"
                    + "\"minute\":0"
                    + "},"
                    + "\"end\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":23,"
                    + "\"minute\":59"
                    + "},"
                    + "\"times\":["
                    + "\"00:00\""
                    + "],"
                    + "\"duration\":720,"
                    + "\"durationUnit\":\"minutes\","
                    + "\"dayOfWeek\":["
                    + "5,"
                    + "6"
                    + "]"
                    + "}"
                    + "}"
                    + "],"
                    + "\"timezones\":{"
                    + "\"" + SiteID + "\":\"America/Toronto\""
                    + "}"
                    + "},"
                    + "\"company\":\"" + CompanyID + "\","
                    + "\"description\":{"
                    + "\"en\":\"This is test update description\""
                    + "},"
                    + "\"items\":{"
                    + "\"main\":["
                    + "{"
                    + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                    + "\"quantity\":1,"
                    + "\"price\":{"
                    + "\"amount\":5"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"French vanilla-Update\""
                    + "},"
                    + "\"discount\":{"
                    + "\"amount_off\":null,"
                    + "\"percent_off\":2"
                    + "}"
                    + "}"
                    + "],"
                    + "\"additional\":["
                    + "]"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"This is API Test for promotion - Limited Time Offer (amount_off)\""
                    + "},"
                    + "\"location_group_ids\":["
                    + "\"" + SiteID + "\""
                    + "],"
                    + "\"multigroup\":\"\","
                    + "\"status\":\"paused\","
                    + "\"meta\":{"
                    + "\"hours\":["
                    + "{"
                    + "\"start\":\"" + PROMO_START_DATE + "\","
                    + "\"end\":\"" + PROMO_START_DATE + "\""
                    + "}"
                    + "],"
                    + "\"promo_start\":\"" + PROMO_START_DATE + "\","
                    + "\"promo_end\":\"" + PROMO_START_DATE + "\""
                    + "},"
                    + "\"type\":\"lto\""
                    + "}";
            JOB_Api_Call("Promotion - PUT Negative flow to update newly added promotion without valid Multipgroup/APP Id", "PUT", BaseAPI + "/promo/" + PROMOTION_IDS.get(0), Auth, BODY, 400, ParentTest, "no_jira");

            // Test Scenario 7: Negative flow to update newly added promotion without valid Company/Group Id
            BODY = "{"
                    + "\"id\":\"" + PROMOTION_IDS.get(0) + "\","
                    + "\"badge\":{"
                    + "\"en\":\"API PROMO-UPDATE\","
                    + "\"fr\":\"API PROMO-UPDATE\""
                    + "},"
                    + "\"calendar\":{"
                    + "\"events\":["
                    + "{"
                    + "\"data\":{"
                    + "\"calendar\":\"hours\""
                    + "},"
                    + "\"schedule\":{"
                    + "\"start\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":0,"
                    + "\"minute\":0"
                    + "},"
                    + "\"end\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":23,"
                    + "\"minute\":59"
                    + "},"
                    + "\"times\":["
                    + "\"00:00\""
                    + "],"
                    + "\"duration\":720,"
                    + "\"durationUnit\":\"minutes\","
                    + "\"dayOfWeek\":["
                    + "5,"
                    + "6"
                    + "]"
                    + "}"
                    + "}"
                    + "],"
                    + "\"timezones\":{"
                    + "\"" + SiteID + "\":\"America/Toronto\""
                    + "}"
                    + "},"
                    + "\"company\":\"\","
                    + "\"description\":{"
                    + "\"en\":\"This is test update description\""
                    + "},"
                    + "\"items\":{"
                    + "\"main\":["
                    + "{"
                    + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                    + "\"quantity\":1,"
                    + "\"price\":{"
                    + "\"amount\":5"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"French vanilla-Update\""
                    + "},"
                    + "\"discount\":{"
                    + "\"amount_off\":null,"
                    + "\"percent_off\":2"
                    + "}"
                    + "}"
                    + "],"
                    + "\"additional\":["
                    + "]"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"This is API Test for promotion - Limited Time Offer (amount_off)\""
                    + "},"
                    + "\"location_group_ids\":["
                    + "\"" + SiteID + "\""
                    + "],"
                    + "\"multigroup\":\"" + AppID + "\","
                    + "\"status\":\"paused\","
                    + "\"meta\":{"
                    + "\"hours\":["
                    + "{"
                    + "\"start\":\"" + PROMO_START_DATE + "\","
                    + "\"end\":\"" + PROMO_START_DATE + "\""
                    + "}"
                    + "],"
                    + "\"promo_start\":\"" + PROMO_START_DATE + "\","
                    + "\"promo_end\":\"" + PROMO_START_DATE + "\""
                    + "},"
                    + "\"type\":\"lto\""
                    + "}";
            JOB_Api_Call("Promotion - PUT Negative flow to update newly added promotion without valid Company/Group Id", "PUT", BaseAPI + "/promo/" + PROMOTION_IDS.get(0), Auth, BODY, 400, ParentTest, "no_jira");

            // Test Scenario 8: Negative flow to update newly added promotion without valid Sector/Site Id
            BODY = "{"
                    + "\"id\":\"" + PROMOTION_IDS.get(0) + "\","
                    + "\"badge\":{"
                    + "\"en\":\"API PROMO-UPDATE\","
                    + "\"fr\":\"API PROMO-UPDATE\""
                    + "},"
                    + "\"calendar\":{"
                    + "\"events\":["
                    + "{"
                    + "\"data\":{"
                    + "\"calendar\":\"hours\""
                    + "},"
                    + "\"schedule\":{"
                    + "\"start\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":0,"
                    + "\"minute\":0"
                    + "},"
                    + "\"end\":{"
                    + "\"year\":" + PROMO_START_YEAR + ","
                    + "\"month\":" + PROMO_START_MONTH + ","
                    + "\"day\":" + PROMO_START_DAY + ","
                    + "\"hour\":23,"
                    + "\"minute\":59"
                    + "},"
                    + "\"times\":["
                    + "\"00:00\""
                    + "],"
                    + "\"duration\":720,"
                    + "\"durationUnit\":\"minutes\","
                    + "\"dayOfWeek\":["
                    + "5,"
                    + "6"
                    + "]"
                    + "}"
                    + "}"
                    + "],"
                    + "\"timezones\":{"
                    + "\"\":\"America/Toronto\""
                    + "}"
                    + "},"
                    + "\"company\":\"" + CompanyID + "\","
                    + "\"description\":{"
                    + "\"en\":\"This is test update description\""
                    + "},"
                    + "\"items\":{"
                    + "\"main\":["
                    + "{"
                    + "\"id\":\"" + ITEMS_IDS.get(0) + "\","
                    + "\"quantity\":1,"
                    + "\"price\":{"
                    + "\"amount\":5"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"French vanilla-Update\""
                    + "},"
                    + "\"discount\":{"
                    + "\"amount_off\":null,"
                    + "\"percent_off\":2"
                    + "}"
                    + "}"
                    + "],"
                    + "\"additional\":["
                    + "]"
                    + "},"
                    + "\"label\":{"
                    + "\"en\":\"This is API Test for promotion - Limited Time Offer (amount_off)\""
                    + "},"
                    + "\"location_group_ids\":["
                    + "\"\""
                    + "],"
                    + "\"multigroup\":\"" + AppID + "\","
                    + "\"status\":\"paused\","
                    + "\"meta\":{"
                    + "\"hours\":["
                    + "{"
                    + "\"start\":\"" + PROMO_START_DATE + "\","
                    + "\"end\":\"" + PROMO_START_DATE + "\""
                    + "}"
                    + "],"
                    + "\"promo_start\":\"" + PROMO_START_DATE + "\","
                    + "\"promo_end\":\"" + PROMO_START_DATE + "\""
                    + "},"
                    + "\"type\":\"lto\""
                    + "}";
            JOB_Api_Call("Promotion - PUT Negative flow to update newly added promotion without valid Sector/Site Id", "PUT", BaseAPI + "/promo/" + PROMOTION_IDS.get(0), Auth, BODY, 400, ParentTest, "no_jira");
        } else {
            //Add fail block, when Item ID equa nullF
        }
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="GET promotions">
        // Test Scenario 1: Positive flow to GET promotions by ID
        JOB_Api_Call("Promotion - GET Positive flow to GET promotions by ID", "GET", BaseAPI + "/promo/" + PROMOTION_IDS.get(0), Auth, BODY, 200, ParentTest, "no_jira");

        //Test Scenario 2:Positive flow Get all promotions within company for a location group
        JOB_Api_Call("Promotion - GET Positive flow Get all promotions within company for a location group", "GET", BaseAPI + "/promo/company" + CompanyID + "/location/group/" + SiteID, Auth, BODY, 200, ParentTest, "no_jira");

        //</editor-fold>
        //<editor-fold defaultstate="collapsed" desc="DELETE promotions">
        // Test Scenario 1: Positive flow to DELETE newly created promotions
        if (PROMOTION_IDS != null) {
            for (int i = 0; i < PROMOTION_IDS.size(); i++) {
                JOB_Api_Call("Promotion - Delete newly created promotion by ID : - " + PROMOTION_IDS.get(i), "DELETE", BaseAPI + "/promo/" + PROMOTION_IDS.get(i), Auth, "", 200, ParentTest, "no_jira");
            }
        }
        //</editor-fold>
    }
}
